In [18]:
pip install openpyxl



     ------------------------------------- 250.0/250.0 kB 97.7 kB/s eta 0:00:00


In [13]:
import pandas as pd

In [59]:
df = pd.read_excel(r'C:\Users\Abhishek\Desktop\marmousi_data.xlsx', header = None)

In [60]:
dc = pd.read_excel(r'C:\Users\Abhishek\Desktop\overthrust.xlsx', header = None)

In [61]:
dd =pd.read_excel(r'C:\Users\Abhishek\Desktop\homogenous_data.xlsx', header = None)

# Marmousi data

In [62]:
df

0       1       2       3       4       5       6       7       8    \
0    1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0   
1    1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0   
2    1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0   
3    1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0   
4    1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
136  4200.0  4300.0  4300.0  4300.0  4300.0  4300.0  3300.0  3300.0  3300.0   
137  4300.0  4300.0  4300.0  4300.0  3300.0  3300.0  3300.0  3300.0  3300.0   
138  4300.0  4300.0  4300.0  3300.0  3300.0  3300.0  3300.0  3300.0  3300.0   
139  4300.0  4300.0  3300.0  3300.0  3300.0  3300.0  3300.0  3300.0  3300.0   
140  4300.0  4300.0  3300.0  3300.0  3300.0  3300.0  3300.0  3300.0  3550.0   

        9    ...     671     672     673     674     675     676     677  \
0    1500.0  ...  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0   
1    1500.0  ...  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0   
2    1500.0  ...  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0   
3    1500.0  ...  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0   
4    1500.0  ...  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0  1500.0   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
136  3300.0  ...  3800.0  3800.0  3800.0  3800.0  3800.0  3800.0  3800.0   
137  3300.0  ...  3800.0  3800.0  3800.0  3800.0  3800.0  3800.0  3800.0   
138  3300.0  ...  3800.0  3800.0  3800.0  3800.0  3800.0  3800.0  3800.0   
139  3550.0  ...  3540.0  3540.0  3800.0  3800.0  3800.0  3800.0  3800.0   
140  3550.0  ...  3540.0  3540.0  3540.0  3800.0  3800.0  3800.0  3800.0   

        678     679     680  
0    1500.0  1500.0  1500.0  
1    1500.0  1500.0  1500.0  
2    1500.0  1500.0  1500.0  
3    1500.0  1500.0  1500.0  
4    1500.0  1500.0  1500.0  
..      ...     ...     ...  
136  3800.0  3800.0  3800.0  
137  3800.0  3800.0  3800.0  
138  3800.0  3800.0  3800.0  
139  3800.0  3800.0  3800.0  
140  3800.0  3800.0  3800.0  

[141 rows x 681 columns]

# overthrust data

In [63]:
dc

0            1            2            3            4    \
0    2592.552734  2597.384521  2602.104492  2606.713135  2611.209473   
1    2593.797119  2598.618896  2603.329346  2607.928711  2612.415527   
2    2602.506592  2607.258789  2611.902344  2616.434814  2620.857178   
3    2626.146240  2630.710693  2635.170410  2639.523682  2643.771484   
4    2672.181885  2676.380127  2680.481934  2684.485596  2688.393311   
..           ...          ...          ...          ...          ...   
182  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000   
183  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000   
184  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000   
185  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000   
186  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000   

             5            6            7            8            9    ...  \
0    2615.593750  2619.866211  2624.025391  2628.073486  2632.007813  ...   
1    2616.791260  2621.054199  2625.206055  2629.244873  2633.171631  ...   
2    2625.169922  2629.372070  2633.463867  2637.444824  2641.315430  ...   
3    2647.913086  2651.949219  2655.878906  2659.702148  2663.419678  ...   
4    2692.202393  2695.914795  2699.529053  2703.045410  2706.464844  ...   
..           ...          ...          ...          ...          ...  ...   
182  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000  ...   
183  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000  ...   
184  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000  ...   
185  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000  ...   
186  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000  ...   

             791          792          793          794          795  \
0    2462.526855  2455.990967  2449.376465  2442.711426  2436.025635   
1    2464.037598  2457.515137  2450.913574  2444.262695  2437.590332   
2    2474.610596  2468.182373  2461.675781  2455.120117  2448.543945   
3    2503.311035  2497.136719  2490.887695  2484.591309  2478.275391   
4    2559.200439  2553.521484  2547.773926  2541.982422  2536.173096   
..           ...          ...          ...          ...          ...   
182  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000   
183  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000   
184  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000   
185  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000   
186  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000   

             796          797          798          799          800  
0    2429.348389  2422.709961  2416.139160  2409.664551  2403.316895  
1    2430.927246  2424.301758  2417.744141  2411.283203  2404.948730  
2    2441.976563  2435.446289  2428.982666  2422.615234  2416.371338  
3    2471.968018  2465.696533  2459.488525  2453.372314  2447.375488  
4    2530.371582  2524.603027  2518.893311  2513.268066  2507.752686  
..           ...          ...          ...          ...          ...  
182  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000  
183  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000  
184  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000  
185  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000  
186  6000.000000  6000.000000  6000.000000  6000.000000  6000.000000  

[187 rows x 801 columns]

# Homogenous data

In [64]:
dd

0     1     2     3     4     5     6     7     8     9   ...    80  \
0   3000  3000  3000  3000  3000  3000  3000  3000  3000  3000  ...  3000   
1   3000  3000  3000  3000  3000  3000  3000  3000  3000  3000  ...  3000   
2   3000  3000  3000  3000  3000  3000  3000  3000  3000  3000  ...  3000   
3   3000  3000  3000  3000  3000  3000  3000  3000  3000  3000  ...  3000   
4   3000  3000  3000  3000  3000  3000  3000  3000  3000  3000  ...  3000   
..   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
85  3000  3000  3000  3000  3000  3000  3000  3000  3000  3000  ...  3000   
86  3000  3000  3000  3000  3000  3000  3000  3000  3000  3000  ...  3000   
87  3000  3000  3000  3000  3000  3000  3000  3000  3000  3000  ...  3000   
88  3000  3000  3000  3000  3000  3000  3000  3000  3000  3000  ...  3000   
89  3000  3000  3000  3000  3000  3000  3000  3000  3000  3000  ...  3000   

      81    82    83    84    85    86    87    88    89  
0   3000  3000  3000  3000  3000  3000  3000  3000  3000  
1   3000  3000  3000  3000  3000  3000  3000  3000  3000  
2   3000  3000  3000  3000  3000  3000  3000  3000  3000  
3   3000  3000  3000  3000  3000  3000  3000  3000  3000  
4   3000  3000  3000  3000  3000  3000  3000  3000  3000  
..   ...   ...   ...   ...   ...   ...   ...   ...   ...  
85  3000  3000  3000  3000  3000  3000  3000  3000  3000  
86  3000  3000  3000  3000  3000  3000  3000  3000  3000  
87  3000  3000  3000  3000  3000  3000  3000  3000  3000  
88  3000  3000  3000  3000  3000  3000  3000  3000  3000  
89  3000  3000  3000  3000  3000  3000  3000  3000  3000  

[90 rows x 90 columns]

In [65]:
numpy_array = df.values
numpy_array1 = dc.values
numpy_array2 = dd.values

In [66]:
import numpy as np
from scipy.io import savemat

# Save the NumPy arrays to a MATLAB file
savemat(r'C:\Users\Abhishek\Desktop\acoustic2dpml-main\acoustic2dpml-main\Examples\Marmousi2\Inputs\marmousi_data.mat', {'variable_name': numpy_array})
savemat(r'C:\Users\Abhishek\Desktop\acoustic2dpml-main\acoustic2dpml-main\Examples\Overthrust\Inputs\overthrust_data.mat', {'dn1': numpy_array1})
savemat(r'C:\Users\Abhishek\Desktop\acoustic2dpml-main\acoustic2dpml-main\Examples\Homogeneous\Inputs\homogenous_data.mat', {'dn1': numpy_array2})


## Adding Noise to our synthetic Marmousi, Overthrust, Homogenous Model

In [71]:
import numpy as np

# Load your overthrust model data into a NumPy array
marmousi_data = numpy_array

# Define the noise level range
min_noise_level = 0.1
max_noise_level = 0.5

# Generate random noise with the same shape as the overthrust data
noise_levels = np.random.uniform(min_noise_level, max_noise_level, size=marmousi_data.shape)
noise = np.random.normal(loc=0, scale=noise_levels, size=marmousi_data.shape)

# Add the noise to the overthrust data
noisy_data = marmousi_data + noise


In [72]:
import numpy as np

# Load your overthrust model data into a NumPy array
overthrust_data = numpy_array1

# Define the noise level range
min_noise_level = 0.1
max_noise_level = 0.5

# Generate random noise with the same shape as the overthrust data
noise_levels = np.random.uniform(min_noise_level, max_noise_level, size=overthrust_data.shape)
noise = np.random.normal(loc=0, scale=noise_levels, size=overthrust_data.shape)

# Add the noise to the overthrust data
noisy_data1 = overthrust_data + noise



In [75]:
import numpy as np

# Load your overthrust model data into a NumPy array
homogenous_data = numpy_array2

# Define the noise level range
min_noise_level = 0.1
max_noise_level = 0.5

# Generate random noise with the same shape as the overthrust data
noise_levels = np.random.uniform(min_noise_level, max_noise_level, size=homogenous_data.shape)
noise = np.random.normal(loc=0, scale=noise_levels, size=homogenous_data.shape)

# Add the noise to the overthrust data
noisy_data2 = homogenous_data + noise



### Noisy Data 

In [73]:
noisy_data

array([[1500.13536889, 1499.94475615, 1500.20215904, ..., 1500.33906601,
        1500.08200003, 1499.98566452],
       [1499.93923026, 1499.96533748, 1499.58239951, ..., 1500.15977436,
        1499.9998714 , 1499.58497506],
       [1499.81633182, 1499.8779642 , 1500.33462482, ..., 1500.02724874,
        1499.85515858, 1499.83176595],
       ...,
       [4300.36188913, 4300.08713691, 4300.00118296, ..., 3799.83510644,
        3799.92933699, 3801.19627739],
       [4299.03663128, 4300.08576915, 3299.44374055, ..., 3799.85722487,
        3800.09193195, 3799.48972924],
       [4300.03185241, 4299.81331332, 3299.84111419, ..., 3800.10376853,
        3799.83579827, 3799.92276539]])

In [74]:
noisy_data1

array([[2592.42931399, 2597.39983366, 2601.98961552, ..., 2416.08413752,
        2409.75061679, 2404.29311822],
       [2593.88121926, 2598.49644207, 2603.37722559, ..., 2418.158097  ,
        2411.51450409, 2405.13554066],
       [2602.2466255 , 2607.28697413, 2612.08907463, ..., 2428.66717309,
        2422.57472223, 2416.00443674],
       ...,
       [6000.23970766, 5999.91423861, 6000.18323581, ..., 6000.28885184,
        6000.01798036, 6000.06010182],
       [5999.77254426, 5999.94279735, 6000.14603143, ..., 6000.11654079,
        6000.27897428, 6000.09857826],
       [6000.19454374, 5999.30878184, 5999.94406372, ..., 5999.90957406,
        5999.55168758, 5999.70040409]])

In [76]:
noisy_data2

array([[3000.54275721, 3000.09475053, 2999.78715259, ..., 2999.9883002 ,
        2999.74487658, 3000.62533302],
       [2999.70073898, 3000.15790572, 3000.03461366, ..., 2999.83325297,
        3000.07745315, 3000.35458754],
       [3000.20355814, 3000.51619986, 3000.00616603, ..., 2999.79420846,
        3000.15918219, 2999.9198419 ],
       ...,
       [2999.8538723 , 3000.11792572, 2999.7461184 , ..., 2999.87813321,
        3000.16351336, 2999.79596214],
       [2999.55218533, 3000.07472087, 3000.65802767, ..., 2999.75344966,
        2999.95531683, 2999.88481577],
       [3000.98490233, 2999.85825824, 3000.29133902, ..., 2999.96932146,
        3000.24735471, 2999.51362215]])

In [77]:
import numpy as np
from scipy.io import savemat

# Save the NumPy arrays to a MATLAB file
savemat(r'C:\Users\Abhishek\Desktop\acoustic2dpml-main\acoustic2dpml-main\Examples\Marmousi2\Inputs\marmousi_data.mat', {'variable_name': numpy_array})
savemat(r'C:\Users\Abhishek\Desktop\acoustic2dpml-main\acoustic2dpml-main\Examples\Overthrust\Inputs\overthrust_data.mat', {'dn1': numpy_array1})
savemat(r'C:\Users\Abhishek\Desktop\acoustic2dpml-main\acoustic2dpml-main\Examples\Homogeneous\Inputs\homogenous_data.mat', {'dn1': noisy_data2})
